# https://taskfile.dev
version: "3"

includes:
  test: ./Taskfile.test.yml
  backup: ./Taskfile.backup.yml

silent: true

tasks:
  all:
    desc: "Run all setup commands"
    cmds:
      - task: setup:starship
      - task: setup:gitignore
      - task: setup:vim
      - task: setup:tldr
      - task: setup:alacritty
      - task: setup:git
      - task: setup:zsh
      - task: setup:fonts

  pkg:golang:
    desc: "Install all Go packages"
    deps: [test:go]
    cmds:
      - go get github.com/cosmtrek/air
      - go get github.com/spf13/cobra/cobra
      - go get github.com/dave/courtney
      - go get github.com/go-delve/delve/cmd/dlv
      - go get github.com/mailru/easyjson
      - go get goa.design/goa/v3/...@v3
      - go get golang.org/x/tools/cmd/goimports
      - go get github.com/segmentio/golines
      - go get github.com/princjef/gomarkdoc/cmd/gomarkdoc
      - go get github.com/magefile/mage
      - go get github.com/client9/misspell/cmd/misspell
      - go get github.com/alphasoc/flightsim/...
      - echo "All Go packages installed!"

  pkg:brew:
    desc: "Install all Brew packages"
    deps: [test:brew]
    cmds:
      - brew install $(tr '\n' ' ' < brewlist.txt)
      - echo "All Brew packages installed!"

  setup:alacritty:
    desc: "Setup Alacritty configuration"
    deps: [test:stow, test:brew]
    cmds:
      - brew install alacritty
      - task: backup:alacritty
      - stow alacritty
      - echo "Alacritty setup!"

  setup:tldr:
    desc: "Setup tldr"
    deps: [test:brew]
    cmds:
      - brew install tldr
      - tldr -u
      - echo "TLDR setup!"

  setup:starship:
    deps: [test:stow, test:brew]
    desc: "Setup Starship prompt"
    cmds:
      - brew install starship
      - task: backup:starship
      - stow --target=$HOME/.config/ starship
      - echo "Starship setup!"

  setup:git:
    desc: "Setup global gitignore"
    deps: [test:git]
    cmds:
      - git config --global core.excludesfile .gitignore-system
      - echo "Global gitignore setup!"

  setup:vim:
    desc: "Setup vimrc"
    deps: [test:stow, test:vimrc]
    cmds:
      - git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
      - sh ~/.vim_runtime/install_awesome_vimrc.sh
      - task: backup:vimrc
      - stow vim
      - echo "VIM setup done!"

  setup:zsh:
    desc: "Setup zsh"
    deps: [test:zsh, test:stow]
    cmds:
      - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - task: backup:zsh
      - stow zsh
      - echo "ZSH setup done!"
    preconditions:
      - sh: test ! -d ~/.oh-my-zsh
        msg: "Please remove ~/.oh-my-zsh"

  setup:fonts:
    desc: "Setup Nerdfonts"
    deps: [test:brew]
    cmds:
      - brew tap homebrew/cask-fonts
      - brew install font-blex-mono-nerd-font
      - brew install font-hack-nerd-font
      - brew install font-jetbrains-mono-nerd-font
      - echo "Fonts setup done!"
